<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="8" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-22T07:48:53 IST" name="Suite" finished-at="2022-12-22T07:49:18 IST" duration-ms="25111">
    <groups>
    </groups>
    <test started-at="2022-12-22T07:48:53 IST" name="Regression" finished-at="2022-12-22T07:49:16 IST" duration-ms="22850">
      <class name="com.Restaurant.Testcases.VerifyvaliduserLoginTest2">
        <test-method is-config="true" signature="firstcall(java.lang.String)[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest2@351d00c0]" started-at="2022-12-22T07:49:08 IST" name="firstcall" finished-at="2022-12-22T07:49:12 IST" duration-ms="4117" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstcall -->
        <test-method signature="VerifyUserLogin()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest2@351d00c0]" started-at="2022-12-22T07:49:12 IST" name="VerifyUserLogin" finished-at="2022-12-22T07:49:16 IST" duration-ms="3267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserLogin -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest2@351d00c0]" started-at="2022-12-22T07:49:16 IST" name="Close" finished-at="2022-12-22T07:49:16 IST" duration-ms="183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- com.Restaurant.Testcases.VerifyvaliduserLoginTest2 -->
      <class name="com.Restaurant.Testcases.VerifyvaliduserLoginTest">
        <test-method is-config="true" signature="firstcall(java.lang.String)[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@6aeb35e6]" started-at="2022-12-22T07:48:53 IST" name="firstcall" finished-at="2022-12-22T07:49:04 IST" duration-ms="10859" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstcall -->
        <test-method signature="VerifyUserLogin()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@6aeb35e6]" started-at="2022-12-22T07:49:04 IST" name="VerifyUserLogin" finished-at="2022-12-22T07:49:07 IST" duration-ms="3550" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.Restaurant.Testcases.VerifyvaliduserLoginTest.VerifyUserLogin(VerifyvaliduserLoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserLogin -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@6aeb35e6]" started-at="2022-12-22T07:49:08 IST" name="Close" finished-at="2022-12-22T07:49:08 IST" duration-ms="263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- com.Restaurant.Testcases.VerifyvaliduserLoginTest -->
    </test> <!-- Regression -->
    <test started-at="2022-12-22T07:48:53 IST" name="Sanity" finished-at="2022-12-22T07:49:18 IST" duration-ms="25111">
      <class name="com.Restaurant.Testcases.VerifyvaliduserLoginTest2">
        <test-method is-config="true" signature="firstcall(java.lang.String)[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest2@2b71e916]" started-at="2022-12-22T07:49:07 IST" name="firstcall" finished-at="2022-12-22T07:49:14 IST" duration-ms="6948" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstcall -->
        <test-method signature="VerifyUserLogin()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest2@2b71e916]" started-at="2022-12-22T07:49:14 IST" name="VerifyUserLogin" finished-at="2022-12-22T07:49:18 IST" duration-ms="3965" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserLogin -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest2@2b71e916]" started-at="2022-12-22T07:49:18 IST" name="Close" finished-at="2022-12-22T07:49:18 IST" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- com.Restaurant.Testcases.VerifyvaliduserLoginTest2 -->
      <class name="com.Restaurant.Testcases.VerifyvaliduserLoginTest">
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@411f53a0]" started-at="2022-12-22T07:48:53 IST" name="loadConfig" finished-at="2022-12-22T07:48:53 IST" duration-ms="348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="firstcall(java.lang.String)[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@411f53a0]" started-at="2022-12-22T07:48:53 IST" name="firstcall" finished-at="2022-12-22T07:49:04 IST" duration-ms="10663" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstcall -->
        <test-method signature="VerifyUserLogin()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@411f53a0]" started-at="2022-12-22T07:49:04 IST" name="VerifyUserLogin" finished-at="2022-12-22T07:49:05 IST" duration-ms="1054" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.Restaurant.Testcases.VerifyvaliduserLoginTest.VerifyUserLogin(VerifyvaliduserLoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserLogin -->
        <test-method is-config="true" signature="Close()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@411f53a0]" started-at="2022-12-22T07:49:07 IST" name="Close" finished-at="2022-12-22T07:49:07 IST" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method is-config="true" signature="Closing()[pri:0, instance:com.Restaurant.Testcases.VerifyvaliduserLoginTest@411f53a0]" started-at="2022-12-22T07:49:18 IST" name="Closing" finished-at="2022-12-22T07:49:19 IST" duration-ms="699" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Closing -->
      </class> <!-- com.Restaurant.Testcases.VerifyvaliduserLoginTest -->
    </test> <!-- Sanity -->
  </suite> <!-- Suite -->
</testng-results>
